version: '2'

services:
  web:
    image: aepyornis/ls-rails:0.1.4
    ports:
        - "8080:80"
        - "8888:8888"
    volumes:
        - ./apps/symfony:/var/www/littlesis/symfony
        - ./apps/rails:/home/app/lilsis
        - ./ls_dev.conf:/etc/nginx/conf.d/site.conf
    depends_on:
        - php
        - memcached
        - mysql
        - mongo
        - rocketchat

  php:
    image: aepyornis/ls-php:v0.0.5
    volumes:
        - ./apps/symfony:/var/www/littlesis/symfony
    depends_on:
      - mysql
      - memcached

  memcached:
    image: memcached:latest
    command: memcached -m 256

  mysql:
    image: mysql:5.5
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root

  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./chat/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MAIL_URL=smtp://smtp.email
      - HTTP_PROXY=http://localhost
      - HTTPS_PROXY=http://localhost
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./chat/db:/data/db
     - ./chat/dump:/dump
    command: mongod --smallfiles
    ports:
      - 27017:27017

    
