web:
    image: ls-rails:v0.0.3
    ports:
        - "8080:80"
    volumes:
        - ./apps/symfony:/var/www/littlesis/symfony
        - ./apps/rails:/home/app/lilsis
        - ./ls_dev.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
        - mysql
php:
    image: ls-php:v0.0.5
    volumes:
        - ./apps/symfony:/var/www/littlesis/symfony
    links:
       - memcached
       - mysql
memcached:
    image: memcached:latest
mysql:
  image: mysql:5.5
  volumes:
    - ./mysql-data:/var/lib/mysql
  ports:
    - '3306:3306'
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=littlesis
    - MYSQL_PASSWORD=themanbehindthemanbehindthethrone
