---
- import_tasks: packages.yml
  tags: packages
- import_tasks: security.yml
- import_tasks: app_user.yml
- import_tasks: rvm.yml
  tags: ruby
- import_tasks: app.yml
  tags: app
- import_tasks: passenger.yml


  
