---
- name: Add Passenger key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: 561F9B9CAC40B2F7

- name: Add passenger Repo
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main'
    state: present
    update_cache: yes

- name: Install Passenger & Nginx
  apt:
    name: "{{ item }}"
  with_items:
    - nginx-extras
    - passenger


- name: Enable passenger in nginx.conf
  lineinfile:
    regexp: 'include /etc/nginx/passenger.conf;'
    line: '  include /etc/nginx/passenger.conf;'
    path: /etc/nginx/nginx.conf
  notify: restart nginx


- name: Validate install
  shell: /usr/bin/passenger-config validate-install --auto
  register: passenger_validate_install
  changed_when: false
  tags: passenger-validate
- debug: msg="{{ passenger_validate_install.stdout_lines }}"
  tags: passenger-validate
