---
- name: Install Redis
  include_role:
    name: DavidWittman.redis
  vars:
    redis_bind: 127.0.0.1
    redis_version: 4.0.7
    redis_verify_checksum: true
    redis_checksum: "sha256:1bba546d44fb40e1fd8be1a15e1a9cc6484bceeea0bbd52919eebc656661ecd1"
