all:
  raw:
    class:      sfDoctrineDatabase
    param:
      dsn:      mysql://littlesis:themanbehindthemanbehindthethrone@172.17.0.3/littlesis_raw

  main:
    class:      sfDoctrineDatabase
    param:
      dsn:      mysql://littlesis:themanbehindthemanbehindthethrone@mysql/littlesis
