all:
  raw:
    class:      sfDoctrineDatabase
    param:
      dsn:      mysql://littlesis:themanbehindthemanbehindthethrone@mysql/littlesis_raw

  main:
    class:      sfDoctrineDatabase
    param:
      dsn:      mysql://littlesis:themanbehindthemanbehindthethrone@mysql/littlesis
