---
- hosts: littlesis
  remote_user: ubuntu
  become: yes

  vars:
    server_name: dev.littlesis.org
    blog_server_name: devnews.littlesis.org

  pre_tasks:
    - name: load secret vars from ~/littlesis.yml
      include_vars:
        file: ~/littlesis.yml
      tags: always

  roles:
    - littlesis
