---
littlesis_packages:
  - curl
  - build-essential
  - git
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - dirmngr
  - htop
  - lsof
  - tmux
  - libcurl4-gnutls-dev
  - imagemagick
  - libmagickwand-dev
  - automake 
  - libffi-dev
  - firefox
  - xvfb
  - python3
  - python3-pip
  - fail2ban

# php
littlesis_php_packages:
  - php7.1
  - php7.1-cli
  - php7.1-common
  - php7.1-json
  - php7.1-opcache
  - php7.1-mysql
  - php7.1-readline
  - php7.1-zip
  - php7.1-xml
  - php7.1-fpm

  
# ssh
kex_algorithms: "diffie-hellman-group-exchange-sha256"
ciphers: "aes256-ctr,aes192-ctr,aes128-ctr"
macs: "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"

# firefox 
geckodriver_url: "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz"

# Swap
swapfile_size: 1G
swapfile_location: /swapfile

# awscli
awscli_region: us-east-1

# nginx
nginx_ssl_ciphers: "'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'"

# nginx passenger
passenger_max_pool_size: 5
passenger_max_requests: 50000
passenger_min_instances: 1

ubuntu_ssh_keys: []

wordpress_restore_from_dump: false
wordpress_sync_uploads: false
wordpress_docker_port: 5000

wordpress_fpm_socket: /var/run/fpm-wordpress.sock
