---
littlesis_packages:
  - curl
  - build-essential
  - git
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - dirmngr
  - htop
  - lsof
  - tmux
  - libcurl4-gnutls-dev
  - imagemagick
  - libmagickwand-dev
  - automake 
  - libffi-dev
  - firefox
  - xvfb
  - fail2ban

# ssh
kex_algorithms: "diffie-hellman-group-exchange-sha256"
ciphers: "aes256-ctr,aes192-ctr,aes128-ctr"
macs: "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"

# ruby
ruby_version: 'ruby-2.3.3'

# firefox 
geckodriver_url: "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz"

# server
server_name: littlesis.org

# Swap
swapfile_size: 1G
swapfile_location: /swapfile


# nginx
dhparam_file: /etc/nginx/certs/dhparam.pem
nginx_ssl_ciphers: "'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'"
